# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1521305556);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1521305676);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1521311976);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1521305436);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1521305916);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1521305316);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1521306036);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1521305796);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 225280);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1521304746);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 59);
user_pref("browser.newtabpage.activity-stream.impressionId", "{cd32bb64-f567-422f-b02d-b17bf46967ac}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1521234000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1521304757);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1521312527379");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1521314329379");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1521311960935");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1521315560935");
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180208175058");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1521305294");
user_pref("browser.slowStartup.averageTime", 6167);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20180208175058");
user_pref("browser.startup.homepage_override.mstone", "58.0.2");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":13,\"newElementCount\":2}");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1521305300120");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "58.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 23);
user_pref("extensions.getAddons.cache.lastUpdate", 1521305557);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180208175058");
user_pref("extensions.lastAppVersion", "58.0.2");
user_pref("extensions.lastPlatformVersion", "58.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("extensions.shield-recipe-client.user_id", "d081d0fe-9da4-479c-8716-f8f24e658e44");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"7fee7b57-ad99-43ad-8e20-b2b9179a6319\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1521306239);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1521305402);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20180208175058");
user_pref("media.gmp-manager.lastCheck", 1521305401);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1521306239);
user_pref("places.history.expiration.transient_current_max_pages", 64312);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("services.blocklist.addons.checked", 1521303446);
user_pref("services.blocklist.clock_skew_seconds", 2230);
user_pref("services.blocklist.gfx.checked", 1521303446);
user_pref("services.blocklist.last_update_seconds", 1521303446);
user_pref("services.blocklist.onecrl.checked", 1521303446);
user_pref("services.blocklist.plugins.checked", 1521303446);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1521306239);
user_pref("toolkit.startup.last_success", 1521305283);
user_pref("toolkit.telemetry.cachedClientID", "f6aa7fef-0208-4bb4-838b-37720c01f502");
user_pref("toolkit.telemetry.previousBuildID", "20180208175058");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
